// Code generated by mcp-cli-gen; DO NOT EDIT.

package main

import "github.com/johejo/mcp-cli-gen/mcpcli"

func main() {
	mcpcli.Run(mcpcli.Snapshot{
		Servers: []mcpcli.ServerSpec{
			{
				Name: "deepwiki",
				URL:  "https://mcp.deepwiki.com/mcp",
			},
		},
		Tools: []mcpcli.ToolSpec{
			{
				Server: "deepwiki",
				Name:   "ask_question",
				Description: []string{
					"Ask any question about a GitHub repository and get an AI-powered, context-grounded response.",
					"",
					"Args:",
					"    repoName: GitHub repository or list of repositories (max 10) in owner/repo format",
					"    question: The question to ask about the repository",
				},
				SchemaJSON: `{
  "properties": {
    "question": {
      "type": "string"
    },
    "repoName": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      ]
    }
  },
  "required": [
    "repoName",
    "question"
  ],
  "type": "object"
}`,
			},
			{
				Server: "deepwiki",
				Name:   "read_wiki_contents",
				Description: []string{
					"View documentation about a GitHub repository.",
					"",
					"Args:",
					"    repoName: GitHub repository in owner/repo format (e.g. \"facebook/react\")",
				},
				SchemaJSON: `{
  "properties": {
    "repoName": {
      "type": "string"
    }
  },
  "required": [
    "repoName"
  ],
  "type": "object"
}`,
			},
			{
				Server: "deepwiki",
				Name:   "read_wiki_structure",
				Description: []string{
					"Get a list of documentation topics for a GitHub repository.",
					"",
					"Args:",
					"    repoName: GitHub repository in owner/repo format (e.g. \"facebook/react\")",
				},
				SchemaJSON: `{
  "properties": {
    "repoName": {
      "type": "string"
    }
  },
  "required": [
    "repoName"
  ],
  "type": "object"
}`,
			},
		},
	}, mcpcli.Options{Flatten: true})
}
