// Code generated by mcp-cli-gen; DO NOT EDIT.

package main

import "github.com/johejo/mcp-cli-gen/mcpcli"

func main() {
	mcpcli.Run(mcpcli.Snapshot{
		Servers: []mcpcli.ServerSpec{
			{
				Name: "github",
				URL:  "https://api.githubcopilot.com/mcp/",
				Headers: map[string]string{
					"Authorization": "Bearer ${GITHUB_PAT}",
				},
			},
		},
		Tools: []mcpcli.ToolSpec{
			{
				Server:      "github",
				Name:        "add_comment_to_pending_review",
				Description: "Add review comment to the requester's latest pending pull request review. A pending review needs to already exist to call this (check with the user if not sure).",
				SchemaJSON:  "{\"properties\":{\"body\":{\"description\":\"The text of the review comment\",\"type\":\"string\"},\"line\":{\"description\":\"The line of the blob in the pull request diff that the comment applies to. For multi-line comments, the last line of the range\",\"type\":\"number\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"path\":{\"description\":\"The relative path to the file that necessitates a comment\",\"type\":\"string\"},\"pullNumber\":{\"description\":\"Pull request number\",\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"side\":{\"description\":\"The side of the diff to comment on. LEFT indicates the previous state, RIGHT indicates the new state\",\"enum\":[\"LEFT\",\"RIGHT\"],\"type\":\"string\"},\"startLine\":{\"description\":\"For multi-line comments, the first line of the range that the comment applies to\",\"type\":\"number\"},\"startSide\":{\"description\":\"For multi-line comments, the starting side of the diff that the comment applies to. LEFT indicates the previous state, RIGHT indicates the new state\",\"enum\":[\"LEFT\",\"RIGHT\"],\"type\":\"string\"},\"subjectType\":{\"description\":\"The level at which the comment is targeted\",\"enum\":[\"FILE\",\"LINE\"],\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"pullNumber\",\"path\",\"body\",\"subjectType\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "add_issue_comment",
				Description: "Add a comment to a specific issue in a GitHub repository. Use this tool to add comments to pull requests as well (in this case pass pull request number as issue_number), but only if user is not asking specifically to add review comments.",
				SchemaJSON:  "{\"properties\":{\"body\":{\"description\":\"Comment content\",\"type\":\"string\"},\"issue_number\":{\"description\":\"Issue number to comment on\",\"type\":\"number\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"issue_number\",\"body\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "add_reply_to_pull_request_comment",
				Description: "Add a reply to an existing pull request comment. This creates a new comment that is linked as a reply to the specified comment.",
				SchemaJSON:  "{\"properties\":{\"body\":{\"description\":\"The text of the reply\",\"type\":\"string\"},\"commentId\":{\"description\":\"The ID of the comment to reply to\",\"type\":\"number\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"pullNumber\":{\"description\":\"Pull request number\",\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"pullNumber\",\"commentId\",\"body\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "create_branch",
				Description: "Create a new branch in a GitHub repository",
				SchemaJSON:  "{\"properties\":{\"branch\":{\"description\":\"Name for new branch\",\"type\":\"string\"},\"from_branch\":{\"description\":\"Source branch (defaults to repo default)\",\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"branch\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "create_or_update_file",
				Description: "Create or update a single file in a GitHub repository. \nIf updating, you should provide the SHA of the file you want to update. Use this tool to create or update a file in a GitHub repository remotely; do not use it for local file operations.\n\nIn order to obtain the SHA of original file version before updating, use the following git command:\ngit rev-parse <branch>:<path to file>\n\nSHA MUST be provided for existing file updates.\n",
				SchemaJSON:  "{\"properties\":{\"branch\":{\"description\":\"Branch to create/update the file in\",\"type\":\"string\"},\"content\":{\"description\":\"Content of the file\",\"type\":\"string\"},\"message\":{\"description\":\"Commit message\",\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner (username or organization)\",\"type\":\"string\"},\"path\":{\"description\":\"Path where to create/update the file\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"sha\":{\"description\":\"The blob SHA of the file being replaced. Required if the file already exists.\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"path\",\"content\",\"message\",\"branch\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "create_pull_request",
				Description: "Create a new pull request in a GitHub repository.",
				SchemaJSON:  "{\"properties\":{\"base\":{\"description\":\"Branch to merge into\",\"type\":\"string\"},\"body\":{\"description\":\"PR description\",\"type\":\"string\"},\"draft\":{\"description\":\"Create as draft PR\",\"type\":\"boolean\"},\"head\":{\"description\":\"Branch containing changes\",\"type\":\"string\"},\"maintainer_can_modify\":{\"description\":\"Allow maintainer edits\",\"type\":\"boolean\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"title\":{\"description\":\"PR title\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"title\",\"head\",\"base\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "create_repository",
				Description: "Create a new GitHub repository in your account or specified organization",
				SchemaJSON:  "{\"properties\":{\"autoInit\":{\"description\":\"Initialize with README\",\"type\":\"boolean\"},\"description\":{\"description\":\"Repository description\",\"type\":\"string\"},\"name\":{\"description\":\"Repository name\",\"type\":\"string\"},\"organization\":{\"description\":\"Organization to create the repository in (omit to create in your personal account)\",\"type\":\"string\"},\"private\":{\"description\":\"Whether repo should be private\",\"type\":\"boolean\"}},\"required\":[\"name\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "delete_file",
				Description: "Delete a file from a GitHub repository",
				SchemaJSON:  "{\"properties\":{\"branch\":{\"description\":\"Branch to delete the file from\",\"type\":\"string\"},\"message\":{\"description\":\"Commit message\",\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner (username or organization)\",\"type\":\"string\"},\"path\":{\"description\":\"Path to the file to delete\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"path\",\"message\",\"branch\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "fork_repository",
				Description: "Fork a GitHub repository to your account or specified organization",
				SchemaJSON:  "{\"properties\":{\"organization\":{\"description\":\"Organization to fork to\",\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "get_commit",
				Description: "Get details for a commit from a GitHub repository",
				SchemaJSON:  "{\"properties\":{\"include_diff\":{\"default\":true,\"description\":\"Whether to include file diffs and stats in the response. Default is true.\",\"type\":\"boolean\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"sha\":{\"description\":\"Commit SHA, branch name, or tag name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"sha\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "get_file_contents",
				Description: "Get the contents of a file or directory from a GitHub repository",
				SchemaJSON:  "{\"properties\":{\"owner\":{\"description\":\"Repository owner (username or organization)\",\"type\":\"string\"},\"path\":{\"default\":\"/\",\"description\":\"Path to file/directory\",\"type\":\"string\"},\"ref\":{\"description\":\"Accepts optional git refs such as `refs/tags/{tag}`, `refs/heads/{branch}` or `refs/pull/{pr_number}/head`\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"sha\":{\"description\":\"Accepts optional commit SHA. If specified, it will be used instead of ref\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "get_label",
				Description: "Get a specific label from a repository.",
				SchemaJSON:  "{\"properties\":{\"name\":{\"description\":\"Label name.\",\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner (username or organization name)\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"name\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "get_latest_release",
				Description: "Get the latest release in a GitHub repository",
				SchemaJSON:  "{\"properties\":{\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "get_me",
				Description: "Get details of the authenticated GitHub user. Use this when a request is about the user's own profile for GitHub. Or when information is missing to build other tool calls.",
				SchemaJSON:  "{\"properties\":{},\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "get_release_by_tag",
				Description: "Get a specific release by its tag name in a GitHub repository",
				SchemaJSON:  "{\"properties\":{\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"tag\":{\"description\":\"Tag name (e.g., 'v1.0.0')\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"tag\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "get_tag",
				Description: "Get details about a specific git tag in a GitHub repository",
				SchemaJSON:  "{\"properties\":{\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"tag\":{\"description\":\"Tag name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"tag\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "get_team_members",
				Description: "Get member usernames of a specific team in an organization. Limited to organizations accessible with current credentials",
				SchemaJSON:  "{\"properties\":{\"org\":{\"description\":\"Organization login (owner) that contains the team.\",\"type\":\"string\"},\"team_slug\":{\"description\":\"Team slug\",\"type\":\"string\"}},\"required\":[\"org\",\"team_slug\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "get_teams",
				Description: "Get details of the teams the user is a member of. Limited to organizations accessible with current credentials",
				SchemaJSON:  "{\"properties\":{\"user\":{\"description\":\"Username to get teams for. If not provided, uses the authenticated user.\",\"type\":\"string\"}},\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "issue_read",
				Description: "Get information about a specific issue in a GitHub repository.",
				SchemaJSON:  "{\"properties\":{\"issue_number\":{\"description\":\"The number of the issue\",\"type\":\"number\"},\"method\":{\"description\":\"The read operation to perform on a single issue.\\nOptions are:\\n1. get - Get details of a specific issue.\\n2. get_comments - Get issue comments.\\n3. get_sub_issues - Get sub-issues of the issue.\\n4. get_labels - Get labels assigned to the issue.\\n\",\"enum\":[\"get\",\"get_comments\",\"get_sub_issues\",\"get_labels\"],\"type\":\"string\"},\"owner\":{\"description\":\"The owner of the repository\",\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"repo\":{\"description\":\"The name of the repository\",\"type\":\"string\"}},\"required\":[\"method\",\"owner\",\"repo\",\"issue_number\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "issue_write",
				Description: "Create a new or update an existing issue in a GitHub repository.",
				SchemaJSON:  "{\"properties\":{\"assignees\":{\"description\":\"Usernames to assign to this issue\",\"items\":{\"type\":\"string\"},\"type\":\"array\"},\"body\":{\"description\":\"Issue body content\",\"type\":\"string\"},\"duplicate_of\":{\"description\":\"Issue number that this issue is a duplicate of. Only used when state_reason is 'duplicate'.\",\"type\":\"number\"},\"issue_number\":{\"description\":\"Issue number to update\",\"type\":\"number\"},\"labels\":{\"description\":\"Labels to apply to this issue\",\"items\":{\"type\":\"string\"},\"type\":\"array\"},\"method\":{\"description\":\"Write operation to perform on a single issue.\\nOptions are:\\n- 'create' - creates a new issue.\\n- 'update' - updates an existing issue.\\n\",\"enum\":[\"create\",\"update\"],\"type\":\"string\"},\"milestone\":{\"description\":\"Milestone number\",\"type\":\"number\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"state\":{\"description\":\"New state\",\"enum\":[\"open\",\"closed\"],\"type\":\"string\"},\"state_reason\":{\"description\":\"Reason for the state change. Ignored unless state is changed.\",\"enum\":[\"completed\",\"not_planned\",\"duplicate\"],\"type\":\"string\"},\"title\":{\"description\":\"Issue title\",\"type\":\"string\"},\"type\":{\"description\":\"Type of this issue. Only use if the repository has issue types configured. Use list_issue_types tool to get valid type values for the organization. If the repository doesn't support issue types, omit this parameter.\",\"type\":\"string\"}},\"required\":[\"method\",\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "list_branches",
				Description: "List branches in a GitHub repository",
				SchemaJSON:  "{\"properties\":{\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "list_commits",
				Description: "Get list of commits of a branch in a GitHub repository. Returns at least 30 results per page by default, but can return more if specified using the perPage parameter (up to 100).",
				SchemaJSON:  "{\"properties\":{\"author\":{\"description\":\"Author username or email address to filter commits by\",\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"path\":{\"description\":\"Only commits containing this file path will be returned\",\"type\":\"string\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"sha\":{\"description\":\"Commit SHA, branch or tag name to list commits of. If not provided, uses the default branch of the repository. If a commit SHA is provided, will list commits up to that SHA.\",\"type\":\"string\"},\"since\":{\"description\":\"Only commits after this date will be returned (ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ or YYYY-MM-DD)\",\"type\":\"string\"},\"until\":{\"description\":\"Only commits before this date will be returned (ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ or YYYY-MM-DD)\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "list_issue_types",
				Description: "List supported issue types for repository owner (organization).",
				SchemaJSON:  "{\"properties\":{\"owner\":{\"description\":\"The organization owner of the repository\",\"type\":\"string\"}},\"required\":[\"owner\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "list_issues",
				Description: "List issues in a GitHub repository. For pagination, use the 'endCursor' from the previous response's 'pageInfo' in the 'after' parameter.",
				SchemaJSON:  "{\"properties\":{\"after\":{\"description\":\"Cursor for pagination. Use the endCursor from the previous page's PageInfo for GraphQL APIs.\",\"type\":\"string\"},\"direction\":{\"description\":\"Order direction. If provided, the 'orderBy' also needs to be provided.\",\"enum\":[\"ASC\",\"DESC\"],\"type\":\"string\"},\"labels\":{\"description\":\"Filter by labels\",\"items\":{\"type\":\"string\"},\"type\":\"array\"},\"orderBy\":{\"description\":\"Order issues by field. If provided, the 'direction' also needs to be provided.\",\"enum\":[\"CREATED_AT\",\"UPDATED_AT\",\"COMMENTS\"],\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"since\":{\"description\":\"Filter by date (ISO 8601 timestamp)\",\"type\":\"string\"},\"state\":{\"description\":\"Filter by state, by default both open and closed issues are returned when not provided\",\"enum\":[\"OPEN\",\"CLOSED\"],\"type\":\"string\"}},\"required\":[\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "list_pull_requests",
				Description: "List pull requests in a GitHub repository. If the user specifies an author, then DO NOT use this tool and use the search_pull_requests tool instead.",
				SchemaJSON:  "{\"properties\":{\"base\":{\"description\":\"Filter by base branch\",\"type\":\"string\"},\"direction\":{\"description\":\"Sort direction\",\"enum\":[\"asc\",\"desc\"],\"type\":\"string\"},\"head\":{\"description\":\"Filter by head user/org and branch\",\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"sort\":{\"description\":\"Sort by\",\"enum\":[\"created\",\"updated\",\"popularity\",\"long-running\"],\"type\":\"string\"},\"state\":{\"description\":\"Filter by state\",\"enum\":[\"open\",\"closed\",\"all\"],\"type\":\"string\"}},\"required\":[\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "list_releases",
				Description: "List releases in a GitHub repository",
				SchemaJSON:  "{\"properties\":{\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "list_tags",
				Description: "List git tags in a GitHub repository",
				SchemaJSON:  "{\"properties\":{\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "merge_pull_request",
				Description: "Merge a pull request in a GitHub repository.",
				SchemaJSON:  "{\"properties\":{\"commit_message\":{\"description\":\"Extra detail for merge commit\",\"type\":\"string\"},\"commit_title\":{\"description\":\"Title for merge commit\",\"type\":\"string\"},\"merge_method\":{\"description\":\"Merge method\",\"enum\":[\"merge\",\"squash\",\"rebase\"],\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"pullNumber\":{\"description\":\"Pull request number\",\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"pullNumber\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "pull_request_read",
				Description: "Get information on a specific pull request in GitHub repository.",
				SchemaJSON:  "{\"properties\":{\"method\":{\"description\":\"Action to specify what pull request data needs to be retrieved from GitHub. \\nPossible options: \\n 1. get - Get details of a specific pull request.\\n 2. get_diff - Get the diff of a pull request.\\n 3. get_status - Get combined commit status of a head commit in a pull request.\\n 4. get_files - Get the list of files changed in a pull request. Use with pagination parameters to control the number of results returned.\\n 5. get_review_comments - Get review threads on a pull request. Each thread contains logically grouped review comments made on the same code location during pull request reviews. Returns threads with metadata (isResolved, isOutdated, isCollapsed) and their associated comments. Use cursor-based pagination (perPage, after) to control results.\\n 6. get_reviews - Get the reviews on a pull request. When asked for review comments, use get_review_comments method.\\n 7. get_comments - Get comments on a pull request. Use this if user doesn't specifically want review comments. Use with pagination parameters to control the number of results returned.\\n 8. get_check_runs - Get check runs for the head commit of a pull request. Check runs are the individual CI/CD jobs and checks that run on the PR.\\n\",\"enum\":[\"get\",\"get_diff\",\"get_status\",\"get_files\",\"get_review_comments\",\"get_reviews\",\"get_comments\",\"get_check_runs\"],\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"pullNumber\":{\"description\":\"Pull request number\",\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"method\",\"owner\",\"repo\",\"pullNumber\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "pull_request_review_write",
				Description: "Create and/or submit, delete review of a pull request.\n\nAvailable methods:\n- create: Create a new review of a pull request. If \"event\" parameter is provided, the review is submitted. If \"event\" is omitted, a pending review is created.\n- submit_pending: Submit an existing pending review of a pull request. This requires that a pending review exists for the current user on the specified pull request. The \"body\" and \"event\" parameters are used when submitting the review.\n- delete_pending: Delete an existing pending review of a pull request. This requires that a pending review exists for the current user on the specified pull request.\n- resolve_thread: Resolve a review thread. Requires only \"threadId\" parameter with the thread's node ID (e.g., PRRT_kwDOxxx). The owner, repo, and pullNumber parameters are not used for this method. Resolving an already-resolved thread is a no-op.\n- unresolve_thread: Unresolve a previously resolved review thread. Requires only \"threadId\" parameter. The owner, repo, and pullNumber parameters are not used for this method. Unresolving an already-unresolved thread is a no-op.\n",
				SchemaJSON:  "{\"properties\":{\"body\":{\"description\":\"Review comment text\",\"type\":\"string\"},\"commitID\":{\"description\":\"SHA of commit to review\",\"type\":\"string\"},\"event\":{\"description\":\"Review action to perform.\",\"enum\":[\"APPROVE\",\"REQUEST_CHANGES\",\"COMMENT\"],\"type\":\"string\"},\"method\":{\"description\":\"The write operation to perform on pull request review.\",\"enum\":[\"create\",\"submit_pending\",\"delete_pending\",\"resolve_thread\",\"unresolve_thread\"],\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"pullNumber\":{\"description\":\"Pull request number\",\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"threadId\":{\"description\":\"The node ID of the review thread (e.g., PRRT_kwDOxxx). Required for resolve_thread and unresolve_thread methods. Get thread IDs from pull_request_read with method get_review_comments.\",\"type\":\"string\"}},\"required\":[\"method\",\"owner\",\"repo\",\"pullNumber\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "push_files",
				Description: "Push multiple files to a GitHub repository in a single commit",
				SchemaJSON:  "{\"properties\":{\"branch\":{\"description\":\"Branch to push to\",\"type\":\"string\"},\"files\":{\"description\":\"Array of file objects to push, each object with path (string) and content (string)\",\"items\":{\"additionalProperties\":false,\"properties\":{\"content\":{\"description\":\"file content\",\"type\":\"string\"},\"path\":{\"description\":\"path to the file\",\"type\":\"string\"}},\"required\":[\"path\",\"content\"],\"type\":\"object\"},\"type\":\"array\"},\"message\":{\"description\":\"Commit message\",\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"branch\",\"files\",\"message\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "request_copilot_review",
				Description: "Request a GitHub Copilot code review for a pull request. Use this for automated feedback on pull requests, usually before requesting a human reviewer.",
				SchemaJSON:  "{\"properties\":{\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"pullNumber\":{\"description\":\"Pull request number\",\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"pullNumber\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "run_secret_scanning",
				Description: "Scan files, content, or recent changes for secrets such as API keys, passwords, tokens, and credentials.\n\nThis tool is intended for targeted scans of specific files, snippets, or diffs provided directly as content. The files parameter accepts either a single string or an array of strings containing raw file contents or diff hunks, and returns detected secrets with their locations and related secret scanning metadata. Content must not be empty. For full repository scanning, other mechanisms are available.\n\nCaveats:\n\n- Only files within the codebase should be scanned. Files outside of the codebase should not be sent.\n- Files listed in .gitignore should be skipped.",
				SchemaJSON:  "{\"properties\":{\"files\":{\"anyOf\":[{\"minLength\":1,\"type\":\"string\"},{\"items\":{\"type\":\"string\"},\"maxItems\":100,\"minItems\":1,\"type\":\"array\"}],\"description\":\"A single string or an array of strings containing file contents, snippets, or diff hunks to scan for secrets. These must be raw contents, not repository file paths.\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"files\",\"owner\",\"repo\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "search_code",
				Description: "Fast and precise code search across ALL GitHub repositories using GitHub's native search engine. Best for finding exact symbols, functions, classes, or specific code patterns.",
				SchemaJSON:  "{\"properties\":{\"order\":{\"description\":\"Sort order for results\",\"enum\":[\"asc\",\"desc\"],\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"query\":{\"description\":\"Search query using GitHub's powerful code search syntax. Examples: 'content:Skill language:Java org:github', 'NOT is:archived language:Python OR language:go', 'repo:github/github-mcp-server'. Supports exact matching, language filters, path filters, and more.\",\"type\":\"string\"},\"sort\":{\"description\":\"Sort field ('indexed' only)\",\"type\":\"string\"}},\"required\":[\"query\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "search_issues",
				Description: "Search for issues in GitHub repositories using issues search syntax already scoped to is:issue",
				SchemaJSON:  "{\"properties\":{\"order\":{\"description\":\"Sort order\",\"enum\":[\"asc\",\"desc\"],\"type\":\"string\"},\"owner\":{\"description\":\"Optional repository owner. If provided with repo, only issues for this repository are listed.\",\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"query\":{\"description\":\"Search query using GitHub issues search syntax\",\"type\":\"string\"},\"repo\":{\"description\":\"Optional repository name. If provided with owner, only issues for this repository are listed.\",\"type\":\"string\"},\"sort\":{\"description\":\"Sort field by number of matches of categories, defaults to best match\",\"enum\":[\"comments\",\"reactions\",\"reactions-+1\",\"reactions--1\",\"reactions-smile\",\"reactions-thinking_face\",\"reactions-heart\",\"reactions-tada\",\"interactions\",\"created\",\"updated\"],\"type\":\"string\"}},\"required\":[\"query\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "search_pull_requests",
				Description: "Search for pull requests in GitHub repositories using issues search syntax already scoped to is:pr",
				SchemaJSON:  "{\"properties\":{\"order\":{\"description\":\"Sort order\",\"enum\":[\"asc\",\"desc\"],\"type\":\"string\"},\"owner\":{\"description\":\"Optional repository owner. If provided with repo, only pull requests for this repository are listed.\",\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"query\":{\"description\":\"Search query using GitHub pull request search syntax\",\"type\":\"string\"},\"repo\":{\"description\":\"Optional repository name. If provided with owner, only pull requests for this repository are listed.\",\"type\":\"string\"},\"sort\":{\"description\":\"Sort field by number of matches of categories, defaults to best match\",\"enum\":[\"comments\",\"reactions\",\"reactions-+1\",\"reactions--1\",\"reactions-smile\",\"reactions-thinking_face\",\"reactions-heart\",\"reactions-tada\",\"interactions\",\"created\",\"updated\"],\"type\":\"string\"}},\"required\":[\"query\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "search_repositories",
				Description: "Find GitHub repositories by name, description, readme, topics, or other metadata. Perfect for discovering projects, finding examples, or locating specific repositories across GitHub.",
				SchemaJSON:  "{\"properties\":{\"minimal_output\":{\"default\":true,\"description\":\"Return minimal repository information (default: true). When false, returns full GitHub API repository objects.\",\"type\":\"boolean\"},\"order\":{\"description\":\"Sort order\",\"enum\":[\"asc\",\"desc\"],\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"query\":{\"description\":\"Repository search query. Examples: 'machine learning in:name stars:\\u003e1000 language:python', 'topic:react', 'user:facebook'. Supports advanced search syntax for precise filtering.\",\"type\":\"string\"},\"sort\":{\"description\":\"Sort repositories by field, defaults to best match\",\"enum\":[\"stars\",\"forks\",\"help-wanted-issues\",\"updated\"],\"type\":\"string\"}},\"required\":[\"query\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "search_users",
				Description: "Find GitHub users by username, real name, or other profile information. Useful for locating developers, contributors, or team members.",
				SchemaJSON:  "{\"properties\":{\"order\":{\"description\":\"Sort order\",\"enum\":[\"asc\",\"desc\"],\"type\":\"string\"},\"page\":{\"description\":\"Page number for pagination (min 1)\",\"minimum\":1,\"type\":\"number\"},\"perPage\":{\"description\":\"Results per page for pagination (min 1, max 100)\",\"maximum\":100,\"minimum\":1,\"type\":\"number\"},\"query\":{\"description\":\"User search query. Examples: 'john smith', 'location:seattle', 'followers:\\u003e100'. Search is automatically scoped to type:user.\",\"type\":\"string\"},\"sort\":{\"description\":\"Sort users by number of followers or repositories, or when the person joined GitHub.\",\"enum\":[\"followers\",\"repositories\",\"joined\"],\"type\":\"string\"}},\"required\":[\"query\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "sub_issue_write",
				Description: "Add a sub-issue to a parent issue in a GitHub repository.",
				SchemaJSON:  "{\"properties\":{\"after_id\":{\"description\":\"The ID of the sub-issue to be prioritized after (either after_id OR before_id should be specified)\",\"type\":\"number\"},\"before_id\":{\"description\":\"The ID of the sub-issue to be prioritized before (either after_id OR before_id should be specified)\",\"type\":\"number\"},\"issue_number\":{\"description\":\"The number of the parent issue\",\"type\":\"number\"},\"method\":{\"description\":\"The action to perform on a single sub-issue\\nOptions are:\\n- 'add' - add a sub-issue to a parent issue in a GitHub repository.\\n- 'remove' - remove a sub-issue from a parent issue in a GitHub repository.\\n- 'reprioritize' - change the order of sub-issues within a parent issue in a GitHub repository. Use either 'after_id' or 'before_id' to specify the new position.\\n\\t\\t\\t\\t\",\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"replace_parent\":{\"description\":\"When true, replaces the sub-issue's current parent issue. Use with 'add' method only.\",\"type\":\"boolean\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"sub_issue_id\":{\"description\":\"The ID of the sub-issue to add. ID is not the same as issue number\",\"type\":\"number\"}},\"required\":[\"method\",\"owner\",\"repo\",\"issue_number\",\"sub_issue_id\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "update_pull_request",
				Description: "Update an existing pull request in a GitHub repository.",
				SchemaJSON:  "{\"properties\":{\"base\":{\"description\":\"New base branch name\",\"type\":\"string\"},\"body\":{\"description\":\"New description\",\"type\":\"string\"},\"draft\":{\"description\":\"Mark pull request as draft (true) or ready for review (false)\",\"type\":\"boolean\"},\"maintainer_can_modify\":{\"description\":\"Allow maintainer edits\",\"type\":\"boolean\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"pullNumber\":{\"description\":\"Pull request number to update\",\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"},\"reviewers\":{\"description\":\"GitHub usernames to request reviews from\",\"items\":{\"type\":\"string\"},\"type\":\"array\"},\"state\":{\"description\":\"New state\",\"enum\":[\"open\",\"closed\"],\"type\":\"string\"},\"title\":{\"description\":\"New title\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"pullNumber\"],\"type\":\"object\"}",
			},
			{
				Server:      "github",
				Name:        "update_pull_request_branch",
				Description: "Update the branch of a pull request with the latest changes from the base branch.",
				SchemaJSON:  "{\"properties\":{\"expectedHeadSha\":{\"description\":\"The expected SHA of the pull request's HEAD ref\",\"type\":\"string\"},\"owner\":{\"description\":\"Repository owner\",\"type\":\"string\"},\"pullNumber\":{\"description\":\"Pull request number\",\"type\":\"number\"},\"repo\":{\"description\":\"Repository name\",\"type\":\"string\"}},\"required\":[\"owner\",\"repo\",\"pullNumber\"],\"type\":\"object\"}",
			},
		},
	})
}
