// Code generated by mcp-cli-gen; DO NOT EDIT.

package main

import "github.com/johejo/mcp-cli-gen/mcpcli"

func main() {
	mcpcli.Run(mcpcli.Snapshot{
		Servers: []mcpcli.ServerSpec{
			{
				Name: "atlassian",
				URL:  "https://mcp.atlassian.com/v1/mcp",
			},
		},
		Tools: []mcpcli.ToolSpec{
			{
				Server: "atlassian",
				Name:   "addCommentToJiraIssue",
				Description: []string{
					"Add comment",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "commentBody": {
      "description": "Comment body",
      "type": "string"
    },
    "commentVisibility": {
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "group",
            "role"
          ],
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "value"
      ],
      "type": "object"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "issueIdOrKey": {
      "description": "Issue ID or key (e.g., PROJ-123 or 10000)",
      "type": "string"
    },
    "responseContentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "issueIdOrKey",
    "commentBody"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "addWorklogToJiraIssue",
				Description: []string{
					"Add or update a worklog on a Jira issue. When worklogId is provided, updates that worklog;",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "commentBody": {
      "description": "Comment body",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "issueIdOrKey": {
      "description": "Issue ID or key (e.g., PROJ-123 or 10000)",
      "type": "string"
    },
    "started": {
      "description": "When the work was started (ISO 8601 date-time, e.g. 2026-03-09T09:00:00.000+0000). If omitted, the worklog is booked at the current date/time.",
      "type": "string"
    },
    "timeSpent": {
      "description": "Time spent (e.g. 2h, 30m, 4d). Required for new worklogs; use to set or change time when updating.",
      "type": "string"
    },
    "visibility": {
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "group",
            "role"
          ],
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "value"
      ],
      "type": "object"
    },
    "worklogId": {
      "description": "ID of an existing worklog to update. If omitted, a new worklog is created.",
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "issueIdOrKey",
    "timeSpent"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "atlassianUserInfo",
				Description: []string{
					"Get current user info",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {},
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "createConfluenceFooterComment",
				Description: []string{
					"Create a footer comment on a page or blog post",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "attachmentId": {
      "description": "Attachment ID to include",
      "type": "string"
    },
    "body": {
      "description": "Page/comment body. When contentFormat is \"html\", use standard HTML for headings (\u003ch1\u003e-\u003ch6\u003e), paragraphs (\u003cp\u003e), bold (\u003cstrong\u003e), italic (\u003cem\u003e), tables (\u003ctable\u003e/\u003cthead\u003e/\u003ctbody\u003e/\u003ctr\u003e/\u003cth\u003e/\u003ctd\u003e), links (\u003ca href=\"URL\"\u003e), code (\u003cpre\u003e\u003ccode class=\"language-python\"\u003e), and lists (\u003cul\u003e/\u003col\u003e/\u003cli\u003e). For Confluence-specific elements use data-type attributes (not CSS classes): Panels: \u003cdiv data-type=\"panel-info|warning|note|success|error\"\u003e\u003cp\u003etext\u003c/p\u003e\u003c/div\u003e. Status lozenge: \u003cspan data-type=\"status\" data-color=\"green|red|yellow|blue|neutral|purple\"\u003eLabel\u003c/span\u003e. Task list: \u003cul data-type=\"task-list\"\u003e\u003cli data-type=\"task-item\"\u003e\u003cinput type=\"checkbox\"\u003e Item\u003c/li\u003e\u003c/ul\u003e. Decision list: \u003cul data-type=\"decision-list\"\u003e\u003cli data-type=\"decision-item\" data-state=\"DECIDED|UNDECIDED\"\u003etext\u003c/li\u003e\u003c/ul\u003e. Expand/collapse: \u003cdetails\u003e\u003csummary\u003eTitle\u003c/summary\u003e\u003cp\u003econtent\u003c/p\u003e\u003c/details\u003e. User mention: \u003cspan data-type=\"mention\" data-user-id=\"ACCOUNT_ID\"\u003e@Name\u003c/span\u003e. Two-column layout: \u003csection data-type=\"layout-two-equal\"\u003e\u003cdiv data-type=\"column\"\u003e\u003cp\u003eLeft\u003c/p\u003e\u003c/div\u003e\u003cdiv data-type=\"column\"\u003e\u003cp\u003eRight\u003c/p\u003e\u003c/div\u003e\u003c/section\u003e. Smart link (inline preview): \u003ca href=\"URL\" data-card-appearance=\"inline\"\u003etext\u003c/a\u003e. Date: \u003ctime datetime=\"YYYY-MM-DD\"\u003elabel\u003c/time\u003e. Never wrap content in \u003chtml\u003e, \u003chead\u003e, or \u003cbody\u003e tags.",
      "type": "string"
    },
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "contentType": {
      "default": "page",
      "description": "Type of content: page or blog post",
      "enum": [
        "page",
        "blog"
      ],
      "type": "string"
    },
    "customContentId": {
      "description": "Custom content ID to include",
      "type": "string"
    },
    "pageId": {
      "description": "Page or blog post ID, or a Confluence tiny link ID (the encoded part from /wiki/x/ URLs, e.g., Fc1bBw)",
      "type": "string"
    },
    "parentCommentId": {
      "description": "Parent comment ID for replies",
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "body"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "createConfluenceInlineComment",
				Description: []string{
					"Create an inline comment on specific text in a page or blog post",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "body": {
      "description": "Page/comment body. When contentFormat is \"html\", use standard HTML for headings (\u003ch1\u003e-\u003ch6\u003e), paragraphs (\u003cp\u003e), bold (\u003cstrong\u003e), italic (\u003cem\u003e), tables (\u003ctable\u003e/\u003cthead\u003e/\u003ctbody\u003e/\u003ctr\u003e/\u003cth\u003e/\u003ctd\u003e), links (\u003ca href=\"URL\"\u003e), code (\u003cpre\u003e\u003ccode class=\"language-python\"\u003e), and lists (\u003cul\u003e/\u003col\u003e/\u003cli\u003e). For Confluence-specific elements use data-type attributes (not CSS classes): Panels: \u003cdiv data-type=\"panel-info|warning|note|success|error\"\u003e\u003cp\u003etext\u003c/p\u003e\u003c/div\u003e. Status lozenge: \u003cspan data-type=\"status\" data-color=\"green|red|yellow|blue|neutral|purple\"\u003eLabel\u003c/span\u003e. Task list: \u003cul data-type=\"task-list\"\u003e\u003cli data-type=\"task-item\"\u003e\u003cinput type=\"checkbox\"\u003e Item\u003c/li\u003e\u003c/ul\u003e. Decision list: \u003cul data-type=\"decision-list\"\u003e\u003cli data-type=\"decision-item\" data-state=\"DECIDED|UNDECIDED\"\u003etext\u003c/li\u003e\u003c/ul\u003e. Expand/collapse: \u003cdetails\u003e\u003csummary\u003eTitle\u003c/summary\u003e\u003cp\u003econtent\u003c/p\u003e\u003c/details\u003e. User mention: \u003cspan data-type=\"mention\" data-user-id=\"ACCOUNT_ID\"\u003e@Name\u003c/span\u003e. Two-column layout: \u003csection data-type=\"layout-two-equal\"\u003e\u003cdiv data-type=\"column\"\u003e\u003cp\u003eLeft\u003c/p\u003e\u003c/div\u003e\u003cdiv data-type=\"column\"\u003e\u003cp\u003eRight\u003c/p\u003e\u003c/div\u003e\u003c/section\u003e. Smart link (inline preview): \u003ca href=\"URL\" data-card-appearance=\"inline\"\u003etext\u003c/a\u003e. Date: \u003ctime datetime=\"YYYY-MM-DD\"\u003elabel\u003c/time\u003e. Never wrap content in \u003chtml\u003e, \u003chead\u003e, or \u003cbody\u003e tags.",
      "type": "string"
    },
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "contentType": {
      "default": "page",
      "description": "Type of content: page or blog post",
      "enum": [
        "page",
        "blog"
      ],
      "type": "string"
    },
    "inlineCommentProperties": {
      "additionalProperties": false,
      "description": "Text selection properties for highlighting",
      "properties": {
        "textSelection": {
          "description": "Text to highlight",
          "type": "string"
        },
        "textSelectionMatchCount": {
          "description": "Total matches on page",
          "type": "number"
        },
        "textSelectionMatchIndex": {
          "description": "Which match to highlight (0-based)",
          "type": "number"
        }
      },
      "required": [
        "textSelection",
        "textSelectionMatchCount",
        "textSelectionMatchIndex"
      ],
      "type": "object"
    },
    "pageId": {
      "description": "Page or blog post ID, or a Confluence tiny link ID (the encoded part from /wiki/x/ URLs, e.g., Fc1bBw)",
      "type": "string"
    },
    "parentCommentId": {
      "description": "Parent comment ID for replies",
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "body"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "createConfluencePage",
				Description: []string{
					"Create a Confluence page or blog post",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "body": {
      "description": "Page/comment body. When contentFormat is \"html\", use standard HTML for headings (\u003ch1\u003e-\u003ch6\u003e), paragraphs (\u003cp\u003e), bold (\u003cstrong\u003e), italic (\u003cem\u003e), tables (\u003ctable\u003e/\u003cthead\u003e/\u003ctbody\u003e/\u003ctr\u003e/\u003cth\u003e/\u003ctd\u003e), links (\u003ca href=\"URL\"\u003e), code (\u003cpre\u003e\u003ccode class=\"language-python\"\u003e), and lists (\u003cul\u003e/\u003col\u003e/\u003cli\u003e). For Confluence-specific elements use data-type attributes (not CSS classes): Panels: \u003cdiv data-type=\"panel-info|warning|note|success|error\"\u003e\u003cp\u003etext\u003c/p\u003e\u003c/div\u003e. Status lozenge: \u003cspan data-type=\"status\" data-color=\"green|red|yellow|blue|neutral|purple\"\u003eLabel\u003c/span\u003e. Task list: \u003cul data-type=\"task-list\"\u003e\u003cli data-type=\"task-item\"\u003e\u003cinput type=\"checkbox\"\u003e Item\u003c/li\u003e\u003c/ul\u003e. Decision list: \u003cul data-type=\"decision-list\"\u003e\u003cli data-type=\"decision-item\" data-state=\"DECIDED|UNDECIDED\"\u003etext\u003c/li\u003e\u003c/ul\u003e. Expand/collapse: \u003cdetails\u003e\u003csummary\u003eTitle\u003c/summary\u003e\u003cp\u003econtent\u003c/p\u003e\u003c/details\u003e. User mention: \u003cspan data-type=\"mention\" data-user-id=\"ACCOUNT_ID\"\u003e@Name\u003c/span\u003e. Two-column layout: \u003csection data-type=\"layout-two-equal\"\u003e\u003cdiv data-type=\"column\"\u003e\u003cp\u003eLeft\u003c/p\u003e\u003c/div\u003e\u003cdiv data-type=\"column\"\u003e\u003cp\u003eRight\u003c/p\u003e\u003c/div\u003e\u003c/section\u003e. Smart link (inline preview): \u003ca href=\"URL\" data-card-appearance=\"inline\"\u003etext\u003c/a\u003e. Date: \u003ctime datetime=\"YYYY-MM-DD\"\u003elabel\u003c/time\u003e. Never wrap content in \u003chtml\u003e, \u003chead\u003e, or \u003cbody\u003e tags.",
      "type": "string"
    },
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "contentType": {
      "default": "page",
      "description": "Type of content: page or blog post",
      "enum": [
        "page",
        "blog"
      ],
      "type": "string"
    },
    "isPrivate": {
      "description": "Make private",
      "type": "boolean"
    },
    "parentId": {
      "description": "Parent page ID (pages only, ignored for blogs)",
      "type": "string"
    },
    "spaceId": {
      "description": "Space ID",
      "type": "string"
    },
    "status": {
      "default": "current",
      "description": "Status (draft for unpublished)",
      "enum": [
        "current",
        "draft"
      ],
      "type": "string"
    },
    "subtype": {
      "description": "Page subtype (pages only, ignored for blogs)",
      "enum": [
        "live"
      ],
      "type": "string"
    },
    "title": {
      "description": "Page or blog post title",
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "spaceId",
    "body"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "createIssueLink",
				Description: []string{
					"Create a link between two Jira issues. For directional link types (e.g. Blocks): inwardIssue = issue that blocks, outwardIssue = issue that is blocked (e.g. \"A is blocked by B\" → inwardIssue: B, outwardIssue: A). Use getIssueLinkTypes if link type is unknown.",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "comment": {
      "description": "Optional comment on the outward issue.",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "inwardIssue": {
      "description": "Inward issue key (e.g. HSP-1).",
      "type": "string"
    },
    "outwardIssue": {
      "description": "Outward issue key (e.g. MKY-1).",
      "type": "string"
    },
    "type": {
      "description": "Link type name (e.g. Duplicate, Blocks, Clones, Relates). Use getIssueLinkTypes to list available types.",
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "inwardIssue",
    "outwardIssue",
    "type"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "createJiraIssue",
				Description: []string{
					"Create issue",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "additional_fields": {
      "additionalProperties": {},
      "description": "REQUIRED for custom fields. This is the ONLY parameter to set priority, labels, custom fields, or any other Jira fields not listed above. Pass a JSON object with field names as keys. Example: {\"priority\": {\"name\": \"High\"}, \"labels\": [\"bug\"], \"customfield_10001\": \"value\"}.",
      "type": "object"
    },
    "assignee_account_id": {
      "description": "Assignee ID",
      "type": "string"
    },
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "description": {
      "description": "Issue description",
      "type": "string"
    },
    "issueTypeName": {
      "description": "Type (Task, Bug, Story)",
      "type": "string"
    },
    "parent": {
      "description": "Parent for subtasks",
      "type": "string"
    },
    "projectKey": {
      "description": "Project key",
      "type": "string"
    },
    "responseContentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "summary": {
      "type": "string"
    },
    "transition": {
      "additionalProperties": false,
      "description": "Optional workflow transition to apply during creation. Use getTransitionsForJiraIssue to find valid transition IDs. Placed at top level of Jira API request, not inside fields.",
      "properties": {
        "id": {
          "description": "The workflow transition ID to apply during issue creation",
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "type": "object"
    }
  },
  "required": [
    "cloudId",
    "projectKey",
    "issueTypeName",
    "summary"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "editJiraIssue",
				Description: []string{
					"Update issue",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "fields": {
      "additionalProperties": {},
      "type": "object"
    },
    "issueIdOrKey": {
      "description": "Issue ID or key (e.g., PROJ-123 or 10000)",
      "type": "string"
    },
    "responseContentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "issueIdOrKey",
    "fields"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "fetch",
				Description: []string{
					"Get details of a Jira issue or Confluence page by ARI (Atlassian Resource Identifier), if the id is not an ARI, then use a different tool to fetch the content",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Not needed for this tool — cloudId is extracted from the ARI automatically",
      "type": "string"
    },
    "id": {
      "description": "Atlassian Resource Identifier (ARI) from search results, e.g., \"ari:cloud:jira:cloudId:issue/10107\" or \"ari:cloud:confluence:cloudId:page/123456789\"",
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getAccessibleAtlassianResources",
				Description: []string{
					"Get cloudId to make tool calls. When a link is provided (e.g. https://site.atlassian.net/*), try passing the site hostname (e.g. site.atlassian.net) as cloudId to other tools first; if that fails, use this tool to list accessible resources.",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {},
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getConfluenceCommentChildren",
				Description: []string{
					"Get reply(child) comments for a comment",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "commentId": {
      "description": "Parent comment ID",
      "type": "string"
    },
    "commentType": {
      "description": "Comment type",
      "enum": [
        "footer",
        "inline"
      ],
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "cursor": {
      "description": "Pagination cursor",
      "type": "string"
    },
    "limit": {
      "description": "Max replies",
      "type": "number"
    },
    "sort": {
      "description": "Sort order",
      "enum": [
        "id",
        "-id",
        "created-date",
        "-created-date"
      ],
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "commentId",
    "commentType"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getConfluencePage",
				Description: []string{
					"Get a Confluence page or blog post by ID, including body content.",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "contentType": {
      "default": "page",
      "description": "Type of content: page or blog post",
      "enum": [
        "page",
        "blog"
      ],
      "type": "string"
    },
    "pageId": {
      "description": "Page or blog post ID, or a Confluence tiny link ID (the encoded part from /wiki/x/ URLs, e.g., Fc1bBw)",
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "pageId"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getConfluencePageDescendants",
				Description: []string{
					"Get child pages of specified page",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "cursor": {
      "description": "Pagination cursor",
      "type": "string"
    },
    "depth": {
      "description": "Max depth",
      "type": "number"
    },
    "limit": {
      "description": "Max descendants",
      "type": "number"
    },
    "pageId": {
      "description": "Page or blog post ID, or a Confluence tiny link ID (the encoded part from /wiki/x/ URLs, e.g., Fc1bBw)",
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "pageId"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getConfluencePageFooterComments",
				Description: []string{
					"Get footer comments for a page or blog post",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "contentType": {
      "default": "page",
      "description": "Type of content: page or blog post",
      "enum": [
        "page",
        "blog"
      ],
      "type": "string"
    },
    "cursor": {
      "description": "Pagination cursor",
      "type": "string"
    },
    "limit": {
      "description": "Max comments",
      "type": "number"
    },
    "pageId": {
      "description": "Page or blog post ID, or a Confluence tiny link ID (the encoded part from /wiki/x/ URLs, e.g., Fc1bBw)",
      "type": "string"
    },
    "sort": {
      "description": "Sort order",
      "enum": [
        "id",
        "-id",
        "created-date",
        "-created-date"
      ],
      "type": "string"
    },
    "status": {
      "default": "current",
      "description": "Comment status",
      "enum": [
        "current",
        "archived",
        "trashed",
        "deleted",
        "historical",
        "draft"
      ],
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "pageId"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getConfluencePageInlineComments",
				Description: []string{
					"Get inline comments for a page or blog post",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "contentType": {
      "default": "page",
      "description": "Type of content: page or blog post",
      "enum": [
        "page",
        "blog"
      ],
      "type": "string"
    },
    "cursor": {
      "description": "Pagination cursor",
      "type": "string"
    },
    "limit": {
      "description": "Max comments",
      "type": "number"
    },
    "pageId": {
      "description": "Page or blog post ID, or a Confluence tiny link ID (the encoded part from /wiki/x/ URLs, e.g., Fc1bBw)",
      "type": "string"
    },
    "resolutionStatus": {
      "default": "open",
      "description": "Resolution status",
      "enum": [
        "resolved",
        "open",
        "dangling",
        "reopened"
      ],
      "type": "string"
    },
    "sort": {
      "description": "Sort order",
      "enum": [
        "id",
        "-id",
        "created-date",
        "-created-date"
      ],
      "type": "string"
    },
    "status": {
      "default": "current",
      "description": "Comment status",
      "enum": [
        "current",
        "archived",
        "trashed",
        "deleted",
        "historical",
        "draft"
      ],
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "pageId"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getConfluenceSpaces",
				Description: []string{
					"Get spaces",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "expand": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      ],
      "description": "Properties to expand"
    },
    "favoritedBy": {
      "description": "User favorites",
      "type": "string"
    },
    "favourite": {
      "description": "Favorite spaces only",
      "type": "boolean"
    },
    "ids": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "items": {
            "type": "number"
          },
          "type": "array"
        }
      ],
      "description": "Space IDs"
    },
    "keys": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      ],
      "description": "Space keys"
    },
    "labels": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      ],
      "description": "Space labels"
    },
    "limit": {
      "description": "Max results (default: 25, max: 250)",
      "type": "number"
    },
    "start": {
      "description": "Start index",
      "type": "number"
    },
    "status": {
      "description": "Space status",
      "enum": [
        "current",
        "archived"
      ],
      "type": "string"
    },
    "type": {
      "description": "Space type",
      "enum": [
        "global",
        "personal"
      ],
      "type": "string"
    }
  },
  "required": [
    "cloudId"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getIssueLinkTypes",
				Description: []string{
					"Get available Jira issue link types (e.g. Blocks, Duplicate, Clones, Relates). For createIssueLink: inwardIssue = blocker, outwardIssue = blocked (e.g. \"A is blocked by B\" → inwardIssue: B, outwardIssue: A).",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    }
  },
  "required": [
    "cloudId"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getJiraIssue",
				Description: []string{
					"Get issue details",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "expand": {
      "type": "string"
    },
    "failFast": {
      "type": "boolean"
    },
    "fields": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "fieldsByKeys": {
      "type": "boolean"
    },
    "issueIdOrKey": {
      "description": "Issue ID or key (e.g., PROJ-123 or 10000)",
      "type": "string"
    },
    "properties": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "responseContentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "updateHistory": {
      "type": "boolean"
    }
  },
  "required": [
    "cloudId",
    "issueIdOrKey"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getJiraIssueRemoteIssueLinks",
				Description: []string{
					"Get remote links",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "globalId": {
      "type": "string"
    },
    "issueIdOrKey": {
      "description": "Issue ID or key (e.g., PROJ-123 or 10000)",
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "issueIdOrKey"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getJiraIssueTypeMetaWithFields",
				Description: []string{
					"Get field metadata",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "issueTypeId": {
      "type": "string"
    },
    "maxResults": {
      "type": "number"
    },
    "projectIdOrKey": {
      "type": "string"
    },
    "startAt": {
      "type": "number"
    }
  },
  "required": [
    "cloudId",
    "projectIdOrKey",
    "issueTypeId"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getJiraProjectIssueTypesMetadata",
				Description: []string{
					"Get issue types",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "maxResults": {
      "default": 50,
      "maximum": 200,
      "type": "number"
    },
    "projectIdOrKey": {
      "type": "string"
    },
    "startAt": {
      "default": 0,
      "type": "number"
    }
  },
  "required": [
    "cloudId",
    "projectIdOrKey"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getPagesInConfluenceSpace",
				Description: []string{
					"Get pages or blog posts in a space",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "contentType": {
      "default": "page",
      "description": "Type of content: page or blog post",
      "enum": [
        "page",
        "blog"
      ],
      "type": "string"
    },
    "cursor": {
      "description": "Pagination cursor",
      "type": "string"
    },
    "limit": {
      "description": "Max results (default: 25, max: 250)",
      "type": "number"
    },
    "sort": {
      "description": "Sort order",
      "enum": [
        "id",
        "-id",
        "created-date",
        "-created-date",
        "modified-date",
        "-modified-date",
        "title",
        "-title"
      ],
      "type": "string"
    },
    "spaceId": {
      "description": "Space ID",
      "type": "string"
    },
    "status": {
      "description": "Page status",
      "enum": [
        "current",
        "archived",
        "deleted",
        "trashed"
      ],
      "type": "string"
    },
    "title": {
      "description": "Title filter",
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "spaceId"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getTransitionsForJiraIssue",
				Description: []string{
					"Get transitions",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "expand": {
      "type": "string"
    },
    "includeUnavailableTransitions": {
      "type": "boolean"
    },
    "issueIdOrKey": {
      "description": "Issue ID or key (e.g., PROJ-123 or 10000)",
      "type": "string"
    },
    "skipRemoteOnlyCondition": {
      "type": "boolean"
    },
    "sortByOpsBarAndStatus": {
      "type": "boolean"
    },
    "transitionId": {
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "issueIdOrKey"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "getVisibleJiraProjects",
				Description: []string{
					"Get projects",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "action": {
      "default": "create",
      "enum": [
        "view",
        "browse",
        "edit",
        "create"
      ],
      "type": "string"
    },
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "expandIssueTypes": {
      "default": true,
      "type": "boolean"
    },
    "maxResults": {
      "default": 50,
      "maximum": 50,
      "type": "number"
    },
    "searchString": {
      "type": "string"
    },
    "startAt": {
      "default": 0,
      "type": "number"
    }
  },
  "required": [
    "cloudId"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "lookupJiraAccountId",
				Description: []string{
					"Lookup user IDs",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "searchString": {
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "searchString"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "search",
				Description: []string{
					"Search Jira and Confluence using Rovo Search, ALWAYS use this tool to search for Jira and Confluence content unless the word CQL or JQL is used in the context",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Not needed for this tool — cloudId is derived from your access token automatically",
      "type": "string"
    },
    "query": {
      "description": "The search query to use for Rovo Search",
      "type": "string"
    }
  },
  "required": [
    "query"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "searchConfluenceUsingCql",
				Description: []string{
					"Search content with CQL",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "cql": {
      "description": "CQL query string (e.g., \"title ~ \"meeting\" AND type = page\")",
      "type": "string"
    },
    "cqlcontext": {
      "description": "CQL context",
      "type": "string"
    },
    "cursor": {
      "description": "Pagination cursor",
      "type": "string"
    },
    "expand": {
      "description": "Properties to expand",
      "type": "string"
    },
    "limit": {
      "description": "Max results (default: 25, max: 250)",
      "type": "number"
    },
    "next": {
      "description": "Include next page link",
      "type": "boolean"
    },
    "prev": {
      "description": "Include previous page link",
      "type": "boolean"
    }
  },
  "required": [
    "cloudId",
    "cql"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "searchJiraIssuesUsingJql",
				Description: []string{
					"Search issues with JQL",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "fields": {
      "default": [
        "summary",
        "description",
        "status",
        "issuetype",
        "priority",
        "created"
      ],
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "jql": {
      "description": "JQL query",
      "type": "string"
    },
    "maxResults": {
      "default": 10,
      "description": "Max (50-100)",
      "maximum": 100,
      "type": "number"
    },
    "nextPageToken": {
      "description": "Page token",
      "type": "string"
    },
    "responseContentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "jql"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "transitionJiraIssue",
				Description: []string{
					"Transition issue status",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "fields": {
      "additionalProperties": {},
      "type": "object"
    },
    "historyMetadata": {
      "additionalProperties": false,
      "properties": {
        "activityDescription": {
          "type": "string"
        },
        "activityDescriptionKey": {
          "type": "string"
        },
        "actor": {
          "additionalProperties": false,
          "properties": {
            "avatarUrl": {
              "type": "string"
            },
            "displayName": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "cause": {
          "additionalProperties": false,
          "properties": {
            "avatarUrl": {
              "type": "string"
            },
            "displayName": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "description": {
          "type": "string"
        },
        "descriptionKey": {
          "type": "string"
        },
        "emailDescription": {
          "type": "string"
        },
        "emailDescriptionKey": {
          "type": "string"
        },
        "extraData": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "generator": {
          "additionalProperties": false,
          "properties": {
            "avatarUrl": {
              "type": "string"
            },
            "displayName": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "issueIdOrKey": {
      "description": "Issue ID or key (e.g., PROJ-123 or 10000)",
      "type": "string"
    },
    "transition": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "type": "object"
    },
    "update": {
      "additionalProperties": {
        "items": {
          "additionalProperties": {},
          "type": "object"
        },
        "type": "array"
      },
      "type": "object"
    }
  },
  "required": [
    "cloudId",
    "issueIdOrKey",
    "transition"
  ],
  "type": "object"
}`,
			},
			{
				Server: "atlassian",
				Name:   "updateConfluencePage",
				Description: []string{
					"Update a Confluence page or blog post",
				},
				SchemaJSON: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "body": {
      "description": "Page/comment body. When contentFormat is \"html\", use standard HTML for headings (\u003ch1\u003e-\u003ch6\u003e), paragraphs (\u003cp\u003e), bold (\u003cstrong\u003e), italic (\u003cem\u003e), tables (\u003ctable\u003e/\u003cthead\u003e/\u003ctbody\u003e/\u003ctr\u003e/\u003cth\u003e/\u003ctd\u003e), links (\u003ca href=\"URL\"\u003e), code (\u003cpre\u003e\u003ccode class=\"language-python\"\u003e), and lists (\u003cul\u003e/\u003col\u003e/\u003cli\u003e). For Confluence-specific elements use data-type attributes (not CSS classes): Panels: \u003cdiv data-type=\"panel-info|warning|note|success|error\"\u003e\u003cp\u003etext\u003c/p\u003e\u003c/div\u003e. Status lozenge: \u003cspan data-type=\"status\" data-color=\"green|red|yellow|blue|neutral|purple\"\u003eLabel\u003c/span\u003e. Task list: \u003cul data-type=\"task-list\"\u003e\u003cli data-type=\"task-item\"\u003e\u003cinput type=\"checkbox\"\u003e Item\u003c/li\u003e\u003c/ul\u003e. Decision list: \u003cul data-type=\"decision-list\"\u003e\u003cli data-type=\"decision-item\" data-state=\"DECIDED|UNDECIDED\"\u003etext\u003c/li\u003e\u003c/ul\u003e. Expand/collapse: \u003cdetails\u003e\u003csummary\u003eTitle\u003c/summary\u003e\u003cp\u003econtent\u003c/p\u003e\u003c/details\u003e. User mention: \u003cspan data-type=\"mention\" data-user-id=\"ACCOUNT_ID\"\u003e@Name\u003c/span\u003e. Two-column layout: \u003csection data-type=\"layout-two-equal\"\u003e\u003cdiv data-type=\"column\"\u003e\u003cp\u003eLeft\u003c/p\u003e\u003c/div\u003e\u003cdiv data-type=\"column\"\u003e\u003cp\u003eRight\u003c/p\u003e\u003c/div\u003e\u003c/section\u003e. Smart link (inline preview): \u003ca href=\"URL\" data-card-appearance=\"inline\"\u003etext\u003c/a\u003e. Date: \u003ctime datetime=\"YYYY-MM-DD\"\u003elabel\u003c/time\u003e. Never wrap content in \u003chtml\u003e, \u003chead\u003e, or \u003cbody\u003e tags.",
      "type": "string"
    },
    "cloudId": {
      "description": "Cloud ID (UUID or site URL)",
      "type": "string"
    },
    "contentFormat": {
      "description": "Content format for page body. Use \"html\" to write or read Confluence content as structured HTML — supports headings, paragraphs, tables, task lists, panels (info/warning/note/success/error), two/three-column layouts, code blocks, and inline formatting. HTML is round-trip safe and preserves inline comments. Use \"markdown\" for simplified plain text. Use \"adf\" (Atlassian Document Format, JSON) for full programmatic fidelity. Defaults to ADF when omitted.",
      "enum": [
        "markdown",
        "adf"
      ],
      "type": "string"
    },
    "contentType": {
      "default": "page",
      "description": "Type of content: page or blog post",
      "enum": [
        "page",
        "blog"
      ],
      "type": "string"
    },
    "includeBody": {
      "default": false,
      "description": "If true, include the page body in the response; if false, omit it to reduce payload size.",
      "type": "boolean"
    },
    "pageId": {
      "description": "Page or blog post ID, or a Confluence tiny link ID (the encoded part from /wiki/x/ URLs, e.g., Fc1bBw)",
      "type": "string"
    },
    "parentId": {
      "description": "Parent page ID (pages only, ignored for blogs)",
      "type": "string"
    },
    "spaceId": {
      "description": "Space ID",
      "type": "string"
    },
    "status": {
      "default": "current",
      "description": "Page status",
      "enum": [
        "current",
        "draft"
      ],
      "type": "string"
    },
    "title": {
      "description": "New title",
      "type": "string"
    },
    "versionMessage": {
      "description": "Version message",
      "type": "string"
    }
  },
  "required": [
    "cloudId",
    "pageId",
    "body"
  ],
  "type": "object"
}`,
			},
		},
	}, mcpcli.Options{Flatten: true})
}
